# Site settings
title: MattHarr.com
description: >
  Home page and portfolio site of web developer Matt Harris

email: mattharr505@gmail.com

logourl: /img/logo.png # Your logo or avatar

author: Matthew Harris

author_thumbnail: /img/user1.png # default author avatar

# Theme additions - please update the default values if you intend to use these variables

google_analytics_id: ""  # Your google analytics ID (e.g. 'UA-XXXXXXXX-X')

theme:

  contact:                          # Contact info, leave blank to ignore
    company:
    address:
    city:     Albuquerque
    state:    NM
    zip:      87107
    country:  USA
    phone: 505-750-1523
    latlng:   35.1107,-106.6100 # (e.g. '39.733536,-104.992611')
    twitter:  matt636               # (e.g. 'https://twitter.com/twitter')
    facebook:               # (e.g. 'https://www.facebook.com/facebook')
    github: https://github.com/MattHarr1s                         # (e.g. 'https://github.com/github')
    instagram:                      # (e.g. 'https://instagram.com/instagram')
    flickr:                         # (e.g. 'groups/2772799@N24/')
    linkedin:                       # (e.g. 'company/example')
    youtube:                        # (e.g. 'channel/UCovWO5keLOLcLu8WdO-ABJw')

  authors:                          # Author attribution data
    john:
      display_name: John Doe
      gravatar:     1985af848d639efd74c6af48f242cfa8  # use hash only (e.g. '1985af848d639efd74c6af48f242cfa8')
      email:                        # (e.g. 'info@example.com')
      web:                          # (e.g. 'https://example.com')
      twitter:                      # (e.g. 'https://twitter.com/twitter')
      facebook:                     # (e.g. 'https://www.facebook.com/facebook')
      github:                       # (e.g. 'https://github.com/github')
      instagram:                    # (e.g. 'https://instagram.com/instagram')
      flickr:                       # (e.g. 'groups/2772799@N24/')
      linkedin:                     # (e.g. 'company/example')
      youtube:                      # (e.g. 'channel/UCovWO5keLOLcLu8WdO-ABJw')

  disqus_id:                        # From your Add This account (e.g. 'bowtieexample')

  addthis_id:                       # From your Add This account (e.g. 'ra-00000a0a00a00aaa')


# Permalinks
permalink:           /:categories/:title/
relative_permalinks: false
highlighter: false


# Pagination config
paginate: 5
paginate_path: /page/:num

# Jekyll build/resource locations

# source:  .
# destination: ./_site
# plugins_dir: null
# layouts_dir: ./_layouts
# data_dir:    ./_data
# includes_dir: ./_includes

# Jekyll Handling Reading
include:    [] # Specify files to be included in build that may be otherwise ignored (e.g. '[.htaccess]')

keep_files: [] # Files/Folders located inside the ./_site folder to be retained on build (e.g.'[.git, .svn]')

# Files/Folders to be excluded from generated '_site' folder
exclude:
  - .gitignore
  - .sass-cache
